import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Heavenly Chocolate Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014312/ecommerce/chocolatecake1.webp",
    rating: "5",
    totalRatings: 25,
    price: "499",
    categoryName: "Chocolate",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Jungle Theme Vanilla Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015508/ecommerce/vanillacake01.webp",
    rating: "5",
    totalRatings: 29,
    price: "800",
    categoryName: "Vanilla",
    isOutOfStock: false,
    offerPercentage: 10,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "2 Tier Strawberry Wedding Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015328/ecommerce/strawberrycake3.webp",
    rating: "5",
    totalRatings: 25,
    price: "1990",
    categoryName: "Strawberry",
    isOutOfStock: false,
    offerPercentage: 7,
    item: "Cake",
    weight: "1.5 kg",
    isBestSeller: false,
    priceCategory: "price1500To2000",
  },
  {
    _id: uuid(),
    title: "Cherry Chocolate Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014777/ecommerce/chocolatecake3.webp",
    rating: "5",
    totalRatings: 40,
    price: "750",
    categoryName: "Chocolate",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: true,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Blueberry Vanilla Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015509/ecommerce/vanillacake04.webp",
    rating: "4",
    totalRatings: 15,
    price: "490",
    categoryName: "Vanilla",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Red Velvet Tall Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014954/ecommerce/redvelvetcake3.webp",
    rating: "4",
    totalRatings: 12,
    price: "600",
    categoryName: "Red Velvet",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Fresh Pineapple Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014828/ecommerce/pineapplemuffin1.webp",
    rating: "4",
    totalRatings: 15,
    price: "60",
    categoryName: "Pineapple",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Muffin",
    weight: "80 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Choco Lava Chocolate Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014336/ecommerce/chocolatemuffin2.webp",
    rating: "4",
    totalRatings: 17,
    price: "80",
    categoryName: "Chocolate",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Muffin",
    weight: "80 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Christmas Theme Vanilla Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015508/ecommerce/vanillacake2.webp",
    rating: "5",
    totalRatings: 32,
    price: "900",
    categoryName: "Vanilla",
    isOutOfStock: true,
    offerPercentage: 10,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Tall Pineapple Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014828/ecommerce/pineapplecake2.webp",
    rating: "4",
    totalRatings: 20,
    price: "650",
    categoryName: "Pineapple",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Plain Vanilla Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015509/ecommerce/vanillamuffin2.webp",
    rating: "4",
    totalRatings: 10,
    price: "49",
    categoryName: "Vanilla",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Muffin",
    weight: "60 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Ferrero Rocher Chocolate Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014336/ecommerce/chocolatemuffin1.webp",
    rating: "5",
    totalRatings: 40,
    price: "100",
    categoryName: "Chocolate",
    isOutOfStock: false,
    offerPercentage: 10,
    item: "Muffin",
    weight: "75 grams",
    isBestSeller: true,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "3 Tier Strawberry Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015328/ecommerce/strawberrycake2.webp",
    rating: "4",
    totalRatings: 70,
    price: "1490",
    categoryName: "Strawberry",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "2.5 kg",
    isBestSeller: true,
    priceCategory: "price1000To1500",
  },
  {
    _id: uuid(),
    title: "Red Velvet Heart Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014954/ecommerce/redvelvetcake1.webp",
    rating: "4",
    totalRatings: 12,
    price: "600",
    categoryName: "Red Velvet",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Christmas Theme Chocolate Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014335/ecommerce/chocolatecake2.webp",
    rating: "5",
    totalRatings: 42,
    price: "900",
    categoryName: "Chocolate",
    isOutOfStock: true,
    offerPercentage: 15,
    item: "Cake",
    weight: "1.5 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Chocolate Rose Designer Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014336/ecommerce/chocolatecake4.webp",
    rating: "4",
    totalRatings: 30,
    price: "800",
    categoryName: "Chocolate",
    isOutOfStock: false,
    offerPercentage: 8,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Red Velvet Choco Chips Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014954/ecommerce/redvelvetmuffin2.webp",
    rating: "4",
    totalRatings: 18,
    price: "60",
    categoryName: "Red Velvet",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Muffin",
    weight: "60 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Mouthwatering Strawberry Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015328/ecommerce/strawberrymuffin1.webp",
    rating: "4",
    totalRatings: 27,
    price: "60",
    categoryName: "Strawberry",
    isOutOfStock: true,
    offerPercentage: 5,
    item: "Muffin",
    weight: "70 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Exotic Pineapple Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014827/ecommerce/pineapplecake1.webp",
    rating: "4",
    totalRatings: 32,
    price: "600",
    categoryName: "Pineapple",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: true,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Cream Red Velvet Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014954/ecommerce/redvelvetmuffin1.webp",
    rating: "4",
    totalRatings: 52,
    price: "75",
    categoryName: "Red Velvet",
    isOutOfStock: false,
    offerPercentage: 5,
    item: "Muffin",
    weight: "80 grams",
    isBestSeller: true,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Tall Fresh Strawberry Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015328/ecommerce/strawberrycake1.webp",
    rating: "4",
    totalRatings: 15,
    price: "800",
    categoryName: "Strawberry",
    isOutOfStock: false,
    offerPercentage: 10,
    item: "Cake",
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Creamy Vanilla Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015509/ecommerce/vanillamuffin1.webp",
    rating: "5",
    totalRatings: 72,
    price: "49",
    categoryName: "Vanilla",
    isOutOfStock: false,
    offerPercentage: 12,
    item: "Muffin",
    weight: "65 grams",
    isBestSeller: true,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Red Velvet Round Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014954/ecommerce/redvelvetcake2.webp",
    rating: "3",
    totalRatings: 40,
    price: "600",
    categoryName: "Red Velvet",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: false,
    priceCategory: "price500To1000",
  },
  {
    _id: uuid(),
    title: "Fresh Pineapple Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647014828/ecommerce/pineapplecake3.webp",
    rating: "3",
    totalRatings: 12,
    price: "480",
    categoryName: "Pineapple",
    isOutOfStock: true,
    offerPercentage: 10,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Creamy Strawberry Muffin",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015328/ecommerce/strawberrymuffin2.webp",
    rating: "4",
    totalRatings: 33,
    price: "75",
    categoryName: "Strawberry",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Muffin",
    weight: "70 grams",
    isBestSeller: false,
    priceCategory: "under500",
  },
  {
    _id: uuid(),
    title: "Designer Vanilla Cake",
    imageUrl:
      "https://res.cloudinary.com/dtrjdcrme/image/upload/v1647015508/ecommerce/vanillacake3.webp",
    rating: "5",
    totalRatings: 42,
    price: "999",
    categoryName: "Vanilla",
    isOutOfStock: false,
    offerPercentage: 0,
    item: "Cake",
    weight: "1/2 kg",
    isBestSeller: true,
    priceCategory: "price500To1000",
  },
];
