// For Filters
export const CHOCOLATE = "Chocolate";
export const VANILLA = "Vanilla";
export const RED_VELVET = "Red Velvet";
export const PINEAPPLE = "Pineapple";
export const STRAWBERRY = "Strawberry";
export const CAKE = "Cake";
export const MUFFIN = "Muffin";
export const CART_OPERATION = "CART_OPERATION";
export const WISHLIST_OPERATION = "WISHLIST_OPERATION";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const ITEMS_FILTER = "ITEMS_FILTER";
export const PRICERANGE_FILTER = "PRICERANGE_FILTER";
export const TOGGLE_STOCK = "TOGGLE_STOCK";
export const SORT = "SORT";
export const RATING = "RATING";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ORDERS = "SET_ORDERS";
